//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgsTests.SurfaceArea {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArgsTests.SurfaceArea.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;FullName&quot;:&quot;PowerArgs, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null&quot;,
        ///    &quot;Types&quot;:
        ///    [
        ///        {
        ///            &quot;FullName&quot;:&quot;PowerArgs.Args&quot;,
        ///            &quot;AssemblyQualifiedName&quot;:&quot;PowerArgs.Args, PowerArgs, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null&quot;,
        ///            &quot;IsEnum&quot;:&quot;False&quot;,
        ///            &quot;IsGenericType&quot;:&quot;False&quot;,
        ///            &quot;Name&quot;:&quot;Args&quot;,
        ///            &quot;IsVisible&quot;:&quot;True&quot;,
        ///            &quot;IsValueType&quot;:&quot;False&quot;,
        ///            &quot;GenericArgumentAssemblyQualifiedNames&quot;:
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string APISurface {
            get {
                return ResourceManager.GetString("APISurface", resourceCulture);
            }
        }
    }
}
