//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgsTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArgsTests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;PhotoManager documentation&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1 class=&quot;program-specific-content&quot;&gt;PhotoManager&lt;/h1&gt;
        ///    &lt;p class=&quot;program-specific-content&quot;&gt;A program that lets you manage a collection of photos in Azure storage containers.&lt;/p&gt;
        ///
        ///    &lt;h2&gt;Usage&lt;/h2&gt;
        ///&lt;pre class=&quot;code-sample&quot;&gt;PhotoManager &amp;lt;action&amp;gt; -options&lt;/pre&gt;
        ///
        ///        &lt;h2&gt;Global options&lt;/h2&gt;
        ///    
        ///
        ///    &lt;table&gt;
        ///        &lt;tr&gt;
        ///            &lt;td class=&quot;option [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PhotoAlbumManagerExpectedBrowserUsage {
            get {
                return ResourceManager.GetString("PhotoAlbumManagerExpectedBrowserUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///A program that lets you manage a collection of photos in Azure storage containers.
        ///
        ///Usage - PhotoManager &lt;action&gt; -options
        ///
        ///Global options
        ///
        ///Option        Description                                                                            
        ///Output (-O)   How much output to display while performing management operations [Default=&apos;Light&apos;]    
        ///              Verbose                                                                                
        ///              Light                                     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PhotoAlbumManagerExpectedConsoleUsage {
            get {
                return ResourceManager.GetString("PhotoAlbumManagerExpectedConsoleUsage", resourceCulture);
            }
        }
    }
}
