//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgsTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArgsTests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id                                            StringValue                       
        ///1                                             Some value here                   
        ///2                                             Some value here                   
        ///3                                             Some value here                   
        ///4                                             Some value here                   
        ///5                                             Some value here                   
        ///End                  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BasicGridExpectedOutput {
            get {
                return ResourceManager.GetString("BasicGridExpectedOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;App&gt;
        ///  &lt;StackPanel AutoSize=&quot;true&quot; Orientation=&quot;Vertical&quot;&gt;
        ///    &lt;StackPanel AutoSize=&quot;true&quot; Orientation=&quot;Horizontal&quot; Fill=&quot;Horizontal&quot;&gt;
        ///      &lt;Spinner Foreground=&quot;Green&quot; IsSpinning=&quot;true&quot;&gt;&lt;/Spinner&gt;
        ///      &lt;Label Text=&quot;Name&quot; Fill=&quot;Horizontal&quot; /&gt;
        ///    &lt;/StackPanel&gt;
        ///    &lt;TextBox Value=&quot;{Customer.Name}&quot; Background=&quot;Gray&quot; Foreground=&quot;Black&quot; /&gt;
        ///    &lt;Button Pressed=&quot;SubmitClicked&quot; Shortcut=&quot;Enter&quot; Text=&quot;Submit&quot;/&gt;
        ///  &lt;/StackPanel&gt;
        ///&lt;/App&gt;.
        /// </summary>
        public static string BasicXmlApp {
            get {
                return ResourceManager.GetString("BasicXmlApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;PhotoManager documentation&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1 class=&quot;program-specific-content&quot;&gt;PhotoManager&lt;/h1&gt;
        ///    &lt;p class=&quot;program-specific-content&quot;&gt;A program that lets you manage a collection of photos in Azure storage containers.&lt;/p&gt;
        ///
        ///    &lt;h2&gt;Usage&lt;/h2&gt;
        ///&lt;pre class=&quot;code-sample&quot;&gt;PhotoManager &amp;lt;action&amp;gt; -options&lt;/pre&gt;
        ///
        ///        &lt;h2&gt;Global options&lt;/h2&gt;
        ///    
        ///
        ///    &lt;table&gt;
        ///        &lt;tr&gt;
        ///            &lt;td class=&quot;option [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PhotoAlbumManagerExpectedBrowserUsage {
            get {
                return ResourceManager.GetString("PhotoAlbumManagerExpectedBrowserUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///A program that lets you manage a collection of photos in Azure storage containers.
        ///
        ///Usage - PhotoManager &lt;action&gt; -options
        ///
        ///GlobalOption   Description
        ///Output (-O)    How much output to display while performing management operations [Default=&apos;Light&apos;] 
        ///               Verbose
        ///               Light
        ///               Quiet
        ///
        ///Actions
        ///
        ///  CreateAlbum &lt;StorageAccountName&gt; &lt;StorageAccountKey&gt; [&lt;Container&gt;] -options - Creates a new album in the target container, creating the container if it does not exist
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PhotoAlbumManagerExpectedConsoleUsage {
            get {
                return ResourceManager.GetString("PhotoAlbumManagerExpectedConsoleUsage", resourceCulture);
            }
        }
    }
}
