name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore PowerArgs.sln
      - name: Build
        run: dotnet build PowerArgs.sln --no-restore
      - name: Test
        run: dotnet test PowerArgs.sln --no-build --verbosity normal 
